export * from './Catalog';
export * from './Checkout';
export * from './Home';
export * from './MyCart';
export * from './NotFound';
export * from './OrderHistory';
export * from './ProductDetails';
export * from './SignIn';
export * from './SignUp';
